# Generated by Django 5.1.7 on 2025-03-08 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('eletric', 'Electric'), ('mechanic', 'Mechanic'), ('health', 'Health'), ('home', 'Home'), ('services', 'Services')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
