# Generated by Django 5.1.7 on 2025-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='employees',
            field=models.ManyToManyField(to='api.employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
