# Generated by Django 5.1.7 on 2025-04-14 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_closes_at_alter_company_opens_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 48, 565716)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 48, 565556)),
        ),
    ]
