# Generated by Django 5.1.7 on 2025-04-16 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_company_email_remove_company_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=999.99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 56, 584785)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 56, 584581)),
        ),
        migrations.AlterField(
            model_name='service',
            name='capable_employees',
            field=models.ManyToManyField(default=[], related_name='capable_employees', to='api.employee'),
        ),
    ]
