# Generated by Django 5.1.7 on 2025-05-02 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_company_closes_at_alter_company_opens_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='identifier',
            field=models.CharField(default='isaactecnologias', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 46, 208841)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 46, 208654)),
        ),
    ]
