# Generated by Django 5.1.7 on 2025-05-08 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_company_keywords_alter_company_closes_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 36, 580970)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 36, 580824)),
        ),
    ]
