# Generated by Django 5.1.7 on 2025-07-23 01:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_company_banner_company_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, default='company_banners/default_company_banner.jpg', null=True, upload_to='company_banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 51, 685337)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 51, 685185)),
        ),
    ]
