# Generated by Django 5.1.7 on 2025-08-21 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_company_banner_alter_company_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 19, 768599)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 19, 768427)),
        ),
    ]
