# Generated by Django 5.1.7 on 2025-08-23 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_booking_session_id_alter_company_closes_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 18, 506849)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 18, 506703)),
        ),
    ]
