# Generated by Django 5.1.7 on 2025-08-23 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_company_closes_at_alter_company_opens_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 46, 860196)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 46, 860044)),
        ),
    ]
