# Generated by Django 5.1.7 on 2025-08-24 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_booking_payment_id_alter_company_closes_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 33, 522726)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 33, 522478)),
        ),
    ]
