# Generated by Django 5.1.7 on 2025-08-30 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_payment_id_booking_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.CharField(blank=True, default='company_banners/default_company_banner.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 4, 474365)),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.CharField(blank=True, default='company_images/default_company_image.png', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 4, 474198)),
        ),
    ]
