# Generated by Django 5.1.7 on 2025-09-02 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_company_banner_alter_company_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_event',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.CharField(blank=True, default='/media/company_banners/default_company_banner.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 17, 386187)),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.CharField(blank=True, default='/media/company_images/default_company_image.png', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 17, 386033)),
        ),
    ]
