# Generated by Django 5.1.7 on 2025-09-02 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_booking_calendar_event_alter_company_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='calendar_event',
            field=models.CharField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='closes_at',
            field=models.TimeField(default=datetime.time(18, 0, 24, 559078)),
        ),
        migrations.AlterField(
            model_name='company',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0, 24, 558913)),
        ),
    ]
