# Generated by Django 5.1.7 on 2025-09-08 12:17

from django.db import migrations

def create_demo_data(apps, schema_editor):
    Company = apps.get_model("api", "Company")
    User = apps.get_model("users", "User")
    Service = apps.get_model("api", "Service")
    Employee = apps.get_model("api", "Employee")

    if not Company.objects.filter(identifier="demo-store").exists():
        company = Company.objects.create(
            name="Demo Store",
            description="Demo Store",
            phone="1234567890",
            identifier="demo-store",
            address="1234567890",
            timezone="America/Sao_Paulo",
        )

        user = User.objects.create(
            email="demo@demo.com",
            password="123456",
            name="Demo",
            phone="1234567890",
            company=company,
            role="OWNER",
        )

        Service.objects.create(
            name="Demo Service",
            description="Demo Service",
            company=company,
            max_duration=60,
            required_employee_amount=1,
            price=100,
        )

        Employee.objects.create(
            name="Demo Employee",
            email="demo@demo.com",
            company=company,
        )
    else:
        print("Demo Store already exists")



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_booking_calendar_event_alter_company_closes_at_and_more'),
    ]

    operations = [
       migrations.RunPython(create_demo_data),
    ]
