# Generated by Django 5.1.7 on 2026-04-09 21:50

from django.db import migrations


SQL_SEED = """
DELETE FROM service WHERE company_id IN (
    SELECT id FROM company WHERE identifier = 'autoshine'
);
DELETE FROM company WHERE identifier = 'autoshine';

WITH new_company AS (
    INSERT INTO company (
        created_at,
        updated_at,
        name,
        identifier,
        description,
        phone,
        work_days,
        opens_at,
        closes_at,
        timezone,
        keywords,
        image,
        banner,
        primary_color,
        is_active,
        address
    ) VALUES (
        NOW(),
        NOW(),
        'Autoshine',
        'autoshine',
        'Estética automotiva premium — lavagem, polimento e cuidado com seu carro. Empresa modelo para preview e demonstração.',
        '5511999999999',
        ARRAY[0, 1, 2, 3, 4, 5]::integer[],
        '08:00:00'::time,
        '18:00:00'::time,
        'America/Sao_Paulo',
        ARRAY[
            'lava-jato',
            'polimento',
            'estética automotiva',
            'cerâmica',
            'preview'
        ]::varchar(64)[],
        '/media/company_images/autoshine_logo.png',
        '/media/company_banners/autoshine_banner.png',
        '#0d47a1',
        true,
        'Av. Paulista, 1000 — Bela Vista, São Paulo/SP'
    )
    RETURNING id
)
INSERT INTO service (
    created_at,
    updated_at,
    name,
    description,
    max_duration,
    price,
    company_id
)
SELECT
    NOW(),
    NOW(),
    v.name,
    v.description,
    v.max_duration,
    v.price,
    new_company.id
FROM
    new_company,
    (
        VALUES
            (
                'Lavagem completa',
                'Limpeza externa, aspiração e painéis. Ideal para manutenção semanal.',
                45,
                89.90::double precision
            ),
            (
                'Polimento + vitrificação',
                'Correção leve de pintura e proteção com vitrificador.',
                180,
                599.00::double precision
            ),
            (
                'Higienização interna',
                'Bancos, carpetes, teto e tratamento antibacteriano.',
                120,
                349.90::double precision
            ),
            (
                'Detailing premium',
                'Pacote completo interno + externo com acabamento showroom.',
                300,
                1299.00::double precision
            )
    ) AS v(name, description, max_duration, price);
"""

SQL_UNSEED = """
DELETE FROM service WHERE company_id IN (
    SELECT id FROM company WHERE identifier = 'autoshine'
);
DELETE FROM company WHERE identifier = 'autoshine';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_SEED, reverse_sql=SQL_UNSEED),
    ]
