export const METADATA = {
  title: "iManage - Profissionais a disposição",
  description: "Generated by create next app",
  applicationName: "iManage",
  keywords: [
    // Geral
    "serviços on-demand",
    "marketplace de serviços",
    "contratação de serviços",
    "app de serviços",
    "prestadores de serviço",

    // Categorias de Serviço
    "conserto e manutenção",
    "limpeza e diarista",
    "encanador e eletricista",
    "pintura e reforma",
    "assistência técnica",
    "personal trainer",
    "aulas particulares",
    "babá e cuidador",
    "pet sitter e banho/tosa",
    "motoboy e entregas",
    "consultoria e freelancer",

    // Funcionalidades
    "pagamento online",
    "agendamento fácil",
    "avaliação de profissionais",
    "busca por localização",
    "atendimento 24h",
    "suporte ao cliente",
    "histórico de pedidos",
  ],
  robots: "index, follow",
  openGraph: {
    title: "iManage - Serviços Profissionais",
    description: "A melhor plataforma para encontrar profissionais qualificados.",
    url: "http://localhost:3000/",
    siteName: "iManage",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj6xxlZVOQE3xdd2B1oB-uIbJTsKvagi7GpQ&s",
        width: 1200,
        height: 630,
        alt: "iManage - Serviços Profissionais",
      },
    ],
    locale: "pt_BR",
    type: "website",
  },
}