# Generated by Django 5.1.7 on 2025-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client')], default='CLIENT'),
        ),
    ]
